language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=django14
  - DJANGO=django15
  - DJANGO=django16
  - DJANGO=django17
  - DJANGO=django18
  - DJANGO=django19
  - DJANGO=django110
  - DJANGO=django111
  - DJANGO=django20
  - DJANGO=django21
  - DJANGO=django22
jobs:
  exclude:
    - python: "2.7"
      env: DJANGO=django20
    - python: "2.7"
      env: DJANGO=django21
    - python: "2.7"
      env: DJANGO=django22

    - python: "3.4"
      env: DJANGO=django14
    - python: "3.4"
      env: DJANGO=django15
    - python: "3.4"
      env: DJANGO=django16
    - python: "3.4"
      env: DJANGO=django21
    - python: "3.4"
      env: DJANGO=django22

    - python: "3.5"
      env: DJANGO=django14
    - python: "3.5"
      env: DJANGO=django15
    - python: "3.5"
      env: DJANGO=django16
    - python: "3.5"
      env: DJANGO=django17

    - python: "3.6"
      env: DJANGO=django14
    - python: "3.6"
      env: DJANGO=django15
    - python: "3.6"
      env: DJANGO=django16
    - python: "3.6"
      env: DJANGO=django17

    - python: "3.7"
      env: DJANGO=django14
    - python: "3.7"
      env: DJANGO=django15
    - python: "3.7"
      env: DJANGO=django16
    - python: "3.7"
      env: DJANGO=django17
    - python: "3.7"
      env: DJANGO=django18
    - python: "3.7"
      env: DJANGO=django19
    - python: "3.7"
      env: DJANGO=django110
    - python: "3.7"
      env: DJANGO=django111

    - python: "3.8"
      env: DJANGO=django14
    - python: "3.8"
      env: DJANGO=django15
    - python: "3.8"
      env: DJANGO=django16
    - python: "3.8"
      env: DJANGO=django17
    - python: "3.8"
      env: DJANGO=django18
    - python: "3.8"
      env: DJANGO=django19
    - python: "3.8"
      env: DJANGO=django110
    - python: "3.8"
      env: DJANGO=django111

before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - TOX_TEST_PASSENV="TRAVIS TRAVIS_JOB_ID TRAVIS_BRANCH" tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_success:
  - codecov
