sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=django14
  - DJANGO=django15
  - DJANGO=django16
  - DJANGO=django17
  - DJANGO=django18
  - DJANGO=django19
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=django17
    - python: "2.6"
      env: DJANGO=django18
    - python: "2.6"
      env: DJANGO=django19

    - python: "3.4"
      env: DJANGO=django14
    - python: "3.4"
      env: DJANGO=django15
    - python: "3.4"
      env: DJANGO=django16
    - python: "3.4"
      env: DJANGO=django17

    - python: "3.5"
      env: DJANGO=django14
    - python: "3.5"
      env: DJANGO=django15
    - python: "3.5"
      env: DJANGO=django16
    - python: "3.5"
      env: DJANGO=django17
install:
  - "pip install tox"
script:
  - tox -e $TRAVIS_PYTHON_VERSION-$DJANGO
